"""Approved 200-topic curriculum catalogue for the 2,000-notebook library."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Topic:
    number: int
    section: str
    course: str
    title: str
    lessons: tuple[str, ...]


FULL_STACK_AI = """
001|Full Stack AI|Python|Python language foundations|Python and Jupyter introduction;Notebook cells and execution order;Python syntax and indentation;Variables and naming;Numeric data types;Strings and booleans;Type conversion;Operators and expressions;Input and formatted output;Foundations practice project
002|Full Stack AI|Python|Control flow and problem solving|Boolean logic;Comparison operators;If statements;Elif and nested conditions;Match-case statements;For loops;While loops;Break continue and loop else;Comprehensions;Control-flow project
003|Full Stack AI|Python|Python collections|Lists;Tuples;Dictionaries;Sets and frozensets;Nested collections;Sequence unpacking;Copying and mutability;Sorting and searching;Collection performance;Contact-book project
004|Full Stack AI|Python|Functions and reusable programming|Function definitions;Parameters and arguments;Default and keyword arguments;Args and kwargs;Return values;Scope and closures;Lambda functions;Higher-order functions;Recursion;Functional application project
005|Full Stack AI|Python|Strings files and data formats|Advanced string methods;Unicode and text encoding;Regular expressions;Pathlib and filesystem paths;Reading and writing text;CSV processing;JSON processing;Dates and times;Data validation;File-processing project
006|Full Stack AI|Python|Object-oriented Python|Objects and classes;Constructors and instance state;Encapsulation and properties;Class and static methods;Inheritance;Polymorphism;Abstract base classes;Composition;Dataclasses;OOP application project
007|Full Stack AI|Python|Advanced Python|Iterables and iterators;Generators;Decorators;Context managers;Type hints;Protocols and duck typing;Descriptors;Asyncio fundamentals;Python internals and memory;Advanced Python project
008|Full Stack AI|Python|Professional Python engineering|Modules and packages;Virtual environments;Dependency management;Configuration and secrets;Exception design;Structured logging;Pytest fundamentals;Mocking and fixtures;Formatting linting and typing;Package and CLI project
009|Full Stack AI|Python|APIs databases and automation|HTTP fundamentals;Requests and responses;REST APIs;API authentication;Pagination and retries;Web-data extraction;SQLite with Python;SQLAlchemy fundamentals;Concurrent automation;API-to-database project
010|Full Stack AI|Python|Python for data and AI|NumPy introduction;pandas introduction;Matplotlib introduction;Exploratory analysis;Scikit-learn interfaces;Preprocessing pipelines;Model serialization;Inference applications;AI API integration;Python capstone
011|Full Stack AI|SQL|Relational database foundations|Databases and RDBMS concepts;Tables rows and columns;Keys and relationships;SQL data types;Creating databases;Creating tables;Altering tables;Inserting data;Updating and deleting;Database foundations lab
012|Full Stack AI|SQL|SQL querying fundamentals|SELECT statements;Column aliases;DISTINCT;WHERE filtering;Comparison operators;Logical operators;NULL handling;Sorting results;Limiting results;Querying practice set
013|Full Stack AI|SQL|Joins and set operations|INNER JOIN;LEFT JOIN;RIGHT and FULL JOIN;Self joins;Cross joins;Multi-table joins;UNION and UNION ALL;INTERSECT and EXCEPT;Join troubleshooting;Multi-table project
014|Full Stack AI|SQL|Aggregations and analytical SQL|Aggregate functions;GROUP BY;HAVING;Conditional aggregation;CASE expressions;Window-function foundations;Ranking functions;Running totals;Lag and lead;Analytics project
015|Full Stack AI|SQL|Database design and integrity|Data modeling;Normalization;Denormalization;Primary and foreign keys;Unique constraints;Check constraints;Index foundations;Views;Stored procedures and functions;Database-design project
016|Full Stack AI|SQL|SQL performance and transactions|Execution plans;Index selection;Sargable predicates;Join performance;Query refactoring;Transactions;ACID properties;Locks and isolation;Deadlocks and recovery;Performance lab
017|Full Stack AI|SQL|SQL for analytics and AI|Data-cleaning SQL;Feature-table creation;Time-series SQL;Cohort analysis;Funnel analysis;Customer segmentation;Data-quality checks;Incremental transformations;SQL testing;Analytics capstone
018|Full Stack AI|Data Science|Data-science foundations|Data-science lifecycle;Business-problem framing;Analytical questions;Data and target definitions;Success metrics;Stakeholder requirements;Assumptions and constraints;Analytical project plans;Reproducibility;Problem-framing case study
019|Full Stack AI|Data Science|Data acquisition and profiling|Data-source identification;CSV and spreadsheet ingestion;Database ingestion;API ingestion;Web-data collection;Schema inspection;Data profiling;Missingness analysis;Quality reporting;Acquisition project
020|Full Stack AI|Data Science|Data cleaning|Missing-value strategies;Duplicate detection;Data-type correction;Text normalization;Date cleaning;Outlier treatment;Invalid-category handling;Cross-field validation;Cleaning pipelines;Cleaning capstone
021|Full Stack AI|Data Science|Exploratory data analysis|Univariate analysis;Bivariate analysis;Multivariate analysis;Distribution analysis;Category comparison;Correlation analysis;Outlier investigation;Time-based exploration;Hypothesis generation;Complete EDA report
022|Full Stack AI|Data Science|Probability and descriptive statistics|Populations and samples;Measures of center;Measures of spread;Percentiles and quantiles;Probability rules;Conditional probability;Random variables;Common distributions;Law of large numbers;Simulation project
023|Full Stack AI|Data Science|Statistical inference and experimentation|Sampling distributions;Confidence intervals;Hypothesis testing;P-values and effect size;T-tests;Chi-square tests;ANOVA;A/B testing;Power and sample size;Experiment-analysis project
024|Full Stack AI|Data Science|Feature engineering|Feature definitions;Missing indicators;Numeric transformations;Categorical encoding;Date and time features;Text features;Interaction features;Feature selection;Leakage prevention;Feature-engineering project
025|Full Stack AI|Data Science|Data visualization and communication|Chart-selection principles;Matplotlib foundations;Seaborn statistical charts;Distribution visualizations;Relationship visualizations;Time-series charts;Dashboard principles;Annotation and storytelling;Misleading-chart prevention;Visualization portfolio
026|Full Stack AI|Data Science|Reproducible and responsible data science|Reproducible notebooks;Data versioning;Experiment tracking;Documentation;Privacy principles;Bias identification;Responsible metrics;Peer review;Production handoff;Data-science capstone
027|Full Stack AI|Machine Learning|Machine-learning foundations|ML problem types;Supervised learning;Unsupervised learning;Features and targets;Training and inference;Generalization;Bias and variance;Underfitting and overfitting;Baselines;First ML project
028|Full Stack AI|Machine Learning|Preprocessing and pipelines|Train-validation-test splits;Missing-value imputation;Categorical encoding;Feature scaling;Transformation pipelines;ColumnTransformer;Class imbalance;Data leakage;Reproducible preprocessing;Pipeline project
029|Full Stack AI|Machine Learning|Linear regression|Regression intuition;Simple linear regression;Multiple regression;Loss functions;Gradient descent;Regression assumptions;Regularization;Regression metrics;Residual analysis;Regression project
030|Full Stack AI|Machine Learning|Classification foundations|Classification problems;Logistic regression;Probabilities and logits;Decision thresholds;Confusion matrix;Precision and recall;ROC and PR curves;Multiclass classification;Calibration;Classification project
031|Full Stack AI|Machine Learning|Trees and ensemble learning|Decision trees;Split criteria;Tree pruning;Random forests;Bagging;Gradient boosting;XGBoost concepts;Feature importance;Ensemble tuning;Ensemble project
032|Full Stack AI|Machine Learning|Classical machine-learning algorithms|K-nearest neighbours;Support-vector machines;Naive Bayes;Linear discriminant analysis;Nearest-centroid models;Algorithm assumptions;Scaling requirements;Complexity comparison;Model selection;Algorithm comparison project
033|Full Stack AI|Machine Learning|Clustering|Clustering foundations;K-means;K-means initialization;Hierarchical clustering;DBSCAN;Gaussian mixtures;Cluster evaluation;Choosing cluster count;Cluster interpretation;Segmentation project
034|Full Stack AI|Machine Learning|Dimensionality reduction and anomaly detection|Curse of dimensionality;Principal component analysis;Explained variance;t-SNE concepts;UMAP concepts;Isolation Forest;Local Outlier Factor;One-class SVM;Anomaly evaluation;Anomaly project
035|Full Stack AI|Machine Learning|Evaluation tuning and explainability|Cross-validation;Metric selection;Grid search;Random search;Bayesian-tuning concepts;Learning curves;Validation curves;Permutation importance;SHAP concepts;Model-review report
036|Full Stack AI|Machine Learning|Production machine learning|Model packaging;Batch inference;Online inference;Model APIs;Input validation;Drift detection;Monitoring;Retraining workflows;Responsible deployment;Production ML capstone
037|Full Stack AI|Artificial Intelligence|AI and intelligent agents|History of AI;AI problem categories;Rational agents;Agent environments;Sensors and actuators;Utility and goals;Reactive agents;Model-based agents;Learning agents;Intelligent-agent project
038|Full Stack AI|Artificial Intelligence|Search algorithms|State-space representation;Breadth-first search;Depth-first search;Uniform-cost search;Greedy search;A-star search;Heuristic design;Bidirectional search;Search performance;Pathfinding project
039|Full Stack AI|Artificial Intelligence|Constraint satisfaction and optimization|Constraint-satisfaction problems;Backtracking;Constraint propagation;Variable-ordering heuristics;Local search;Hill climbing;Simulated annealing;Genetic algorithms;Optimization evaluation;Scheduling project
040|Full Stack AI|Artificial Intelligence|Knowledge representation and reasoning|Propositional logic;Predicate logic;Inference rules;Knowledge graphs;Semantic networks;Ontologies;Rule-based systems;Forward chaining;Backward chaining;Expert-system project
041|Full Stack AI|Artificial Intelligence|Planning and decision-making|Planning problems;STRIPS representation;Forward planning;Backward planning;Partial-order planning;Utility theory;Decision trees;Markov decision processes;Policy evaluation;Planning-agent project
042|Full Stack AI|Artificial Intelligence|Probabilistic AI and reinforcement learning|Uncertainty in AI;Bayesian networks;Hidden Markov models;Maximum likelihood;Reinforcement-learning foundations;Multi-armed bandits;Q-learning;Policy learning;Exploration versus exploitation;RL project
043|Full Stack AI|Artificial Intelligence|Responsible and applied AI|AI fairness;Explainability;Privacy;Robustness;Human oversight;AI security;AI governance;Impact assessment;Applied AI architecture;Responsible-AI capstone
044|Full Stack AI|Deep Learning|Neural-network foundations|Neurons and layers;Tensors;Forward propagation;Activation functions;Loss functions;Backpropagation;Computational graphs;Weight initialization;First network;Neural-network project
045|Full Stack AI|Deep Learning|Deep-learning optimization|Gradient-descent review;Stochastic gradient descent;Momentum;RMSProp;Adam;Learning-rate schedules;Batch normalization;Dropout;Regularization;Optimization experiment
046|Full Stack AI|Deep Learning|Convolutional neural networks|Image tensors;Convolution operation;Filters and feature maps;Padding and stride;Pooling;CNN architectures;Image augmentation;Transfer learning;CNN evaluation;Image-classification project
047|Full Stack AI|Deep Learning|Sequence models|Sequential data;Recurrent neural networks;Vanishing gradients;LSTM;GRU;Bidirectional models;Sequence classification;Time-series forecasting;Sequence evaluation;Sequence-model project
048|Full Stack AI|Deep Learning|Attention and transformers|Attention intuition;Query key and value;Scaled dot-product attention;Multi-head attention;Positional encoding;Transformer encoders;Transformer decoders;Masked attention;Transformer implementation;Transformer project
049|Full Stack AI|Deep Learning|Autoencoders and generative deep learning|Autoencoders;Latent representations;Denoising autoencoders;Variational autoencoders;Generative adversarial networks;GAN training;Diffusion-model intuition;Conditional generation;Generative evaluation;Generative project
050|Full Stack AI|Deep Learning|Deep-learning engineering|Dataset pipelines;GPU fundamentals;Training loops;Checkpointing;Mixed precision;Distributed-training concepts;Hyperparameter tuning;Experiment tracking;Model serving;Training-system project
051|Full Stack AI|Deep Learning|Applied deep learning|Computer-vision workflow;NLP workflow;Audio workflow;Multimodal learning;Recommendation models;Anomaly detection;Explainability;Robustness;Responsible deep learning;Deep-learning capstone
052|Full Stack AI|Generative AI|Generative-AI foundations|Generative versus discriminative models;Generative-AI ecosystem;Foundation models;Model modalities;Tokens and context;Sampling;Temperature and top-p;Hallucination;Application patterns;First GenAI application
053|Full Stack AI|Generative AI|Prompt engineering|Prompt anatomy;Instruction design;Context design;Zero-shot prompting;Few-shot prompting;Reasoning prompts;Role prompting;Prompt templates;Prompt testing;Prompt-engineering project
054|Full Stack AI|Generative AI|Text-generation applications|Summarization;Classification;Information extraction;Question answering;Translation;Content generation;Structured output;Tool-assisted generation;Output validation;Text-application project
055|Full Stack AI|Generative AI|Image and multimodal generation|Image-generation foundations;Text-to-image prompting;Image editing;Vision-language models;Image understanding;Document intelligence;Audio-generation concepts;Multimodal workflows;Multimodal safety;Multimodal project
056|Full Stack AI|Generative AI|Generative-AI evaluation and safety|Evaluation strategy;Reference-based evaluation;LLM-as-judge;Human evaluation;Hallucination evaluation;Prompt injection;Content safety;Privacy protection;Red teaming;Safety-evaluation project
057|Full Stack AI|Generative AI|Generative-AI application engineering|Model APIs;Streaming responses;Conversation state;Structured schemas;Function calling;Caching;Cost control;Error handling;Application observability;GenAI application project
058|Full Stack AI|Generative AI|Adaptation and production GenAI|Model-selection strategy;Fine-tuning concepts;Instruction datasets;Preference optimization;Synthetic data;Model deployment;Latency optimization;Production monitoring;Governance;Generative-AI capstone
059|Full Stack AI|Large Language Models|Tokenization and embeddings|Text tokenization;Subword algorithms;Vocabulary construction;Token IDs;Context windows;Word embeddings;Sentence embeddings;Similarity metrics;Embedding evaluation;Embedding project
060|Full Stack AI|Large Language Models|Transformer internals|Transformer architecture;Self-attention mathematics;Multi-head attention;Feed-forward layers;Residual connections;Layer normalization;Positional information;Causal masking;Training objectives;Mini-transformer implementation
061|Full Stack AI|Large Language Models|Advanced LLM prompting|System instructions;Context management;Few-shot examples;Reasoning strategies;Decomposition;Self-consistency;Structured output;Tool-selection prompts;Prompt versioning;Prompt-system project
062|Full Stack AI|Large Language Models|LLM adaptation|Fine-tuning foundations;Dataset preparation;Supervised fine-tuning;LoRA;Quantized LoRA;Preference datasets;DPO concepts;Model merging;Adaptation evaluation;Fine-tuning project
063|Full Stack AI|Large Language Models|LLM inference and optimization|Decoding strategies;KV cache;Batching;Quantization;Distillation;Speculative decoding;Model routing;Latency measurement;Cost optimization;Inference benchmark
064|Full Stack AI|Large Language Models|LLM evaluation and safety|Evaluation datasets;Task metrics;Factuality;Relevance;Groundedness;Bias evaluation;Toxicity evaluation;Jailbreak testing;Human-review design;LLM safety report
065|Full Stack AI|Large Language Models|LLM application engineering|Chat architecture;Conversation memory;Structured extraction;Tool calling;Retrieval integration;Response streaming;Guardrails;Testing;Observability;LLM application project
066|Full Stack AI|Large Language Models|LLMOps and production systems|Model gateways;Prompt registries;Evaluation pipelines;Deployment strategies;Rate limiting;Caching;Tracing;Feedback collection;Governance;Production-LLM capstone
067|Full Stack AI|RAG|RAG foundations|Why retrieval is needed;RAG architecture;Knowledge sources;Indexing lifecycle;Query lifecycle;Retrieval versus fine-tuning;Grounded generation;Citations;RAG failure modes;First RAG system
068|Full Stack AI|RAG|Document ingestion and chunking|Document loaders;PDF extraction;HTML extraction;Metadata design;Text cleaning;Fixed-size chunking;Semantic chunking;Parent-child chunking;Ingestion validation;Ingestion pipeline project
069|Full Stack AI|RAG|Embeddings and vector stores|Embedding models;Dense vectors;Similarity search;Vector indexing;Vector databases;Metadata filtering;Namespace design;Index updates;Embedding evaluation;Vector-store project
070|Full Stack AI|RAG|Retrieval and reranking|Dense retrieval;Sparse retrieval;BM25;Hybrid search;Query rewriting;Multi-query retrieval;Reranking;Context compression;Retrieval metrics;Retrieval benchmark
071|Full Stack AI|RAG|RAG generation and evaluation|Context assembly;Grounding prompts;Citation generation;Abstention;Answer relevance;Context relevance;Faithfulness;End-to-end evaluation;Error analysis;RAG evaluation project
072|Full Stack AI|RAG|Advanced production RAG|Conversational RAG;Graph RAG;Multimodal RAG;Agentic retrieval;Access-controlled retrieval;Caching;Observability;Scaling;Security;Production-RAG capstone
073|Full Stack AI|Agentic AI|Agentic-AI foundations|Agents versus workflows;Agent components;Goals and tasks;Environment modeling;Actions and observations;Agent loops;Deterministic workflows;Autonomy levels;Failure modes;First agent
074|Full Stack AI|Agentic AI|Tools and function calling|Tool definitions;JSON schemas;Tool selection;Argument validation;Tool execution;Error handling;Tool permissions;Parallel tools;Tool-result grounding;Tool-using agent project
075|Full Stack AI|Agentic AI|Planning and reasoning|Task decomposition;Plan generation;ReAct pattern;Plan-and-execute;Reflection;Self-correction;Search-based planning;Budget-aware planning;Plan evaluation;Planning-agent project
076|Full Stack AI|Agentic AI|Agent memory and state|Conversation state;Working memory;Long-term memory;Episodic memory;Semantic memory;Memory retrieval;Memory summarization;State machines;Privacy and retention;Stateful-agent project
077|Full Stack AI|Agentic AI|Multi-agent systems|Multi-agent foundations;Agent roles;Delegation;Handoffs;Shared state;Debate patterns;Supervisor patterns;Coordination failures;Multi-agent evaluation;Multi-agent project
078|Full Stack AI|Agentic AI|Agent security and guardrails|Prompt injection;Tool abuse;Least privilege;Sandboxing;Human approval;Input validation;Output validation;Policy enforcement;Incident handling;Secure-agent project
079|Full Stack AI|Agentic AI|Agent evaluation and observability|Success criteria;Trajectory evaluation;Tool-call evaluation;Planning evaluation;Cost and latency;Tracing;Failure classification;Regression suites;Human evaluation;Agent-evaluation system
080|Full Stack AI|Agentic AI|Production agentic systems|Agent architecture;Durable execution;Queues and scheduling;Retry policies;State persistence;Monitoring;Cost governance;Deployment;Operational runbooks;Agentic-AI capstone
"""


AZURE_DATA_ENGINEERING = """
081|Azure Data Engineering|Python|Python pipeline foundations|Pipeline architecture;Extract transform and load;Pure transformations;Pipeline configuration;Environment variables;Command-line parameters;Checkpointing;Idempotency;Pipeline metadata;Batch-pipeline project
082|Azure Data Engineering|Python|Files and serialization|Filesystem ingestion;CSV pipelines;JSON pipelines;JSON Lines;Parquet concepts;Avro concepts;Compression;Schema validation;File partitioning;Multi-format project
083|Azure Data Engineering|Python|API data ingestion|API-source design;Authentication;Pagination;Rate limits;Retries;Incremental extraction;Watermarks;Response validation;Raw-data preservation;API-ingestion project
084|Azure Data Engineering|Python|Reliable data-engineering Python|Exception strategy;Structured logging;Metrics;Unit testing;Integration testing;Test fixtures;Data-quality tests;Secrets management;Packaging;Tested-pipeline project
085|Azure Data Engineering|Python|Python performance and orchestration|Profiling;Memory-efficient iteration;Chunk processing;Threaded I/O;Process parallelism;Async ingestion;Scheduling;Backfills;Recovery workflows;Python data-engineering capstone
086|Azure Data Engineering|SQL|Staging and ingestion SQL|Staging-table design;Bulk loading;Data-type validation;Reject tables;Deduplication;Watermarks;Incremental loads;Merge operations;Audit columns;Staging project
087|Azure Data Engineering|SQL|Transformation SQL|Cleaning transformations;Standardization;Surrogate keys;Slowly changing dimensions;Fact-table loading;Snapshot tables;Pivoting;Window transformations;Reusable SQL models;Transformation project
088|Azure Data Engineering|SQL|Warehouse SQL|Dimensional queries;Star-schema joins;Time dimensions;Semi-additive measures;Period comparisons;Cohort queries;Materialized views;Aggregate tables;Serving-layer design;Warehouse project
089|Azure Data Engineering|SQL|SQL performance engineering|Execution plans;Indexing;Partition pruning;Statistics;Join strategies;Data distribution;Query rewrites;Workload management;Performance baselines;Tuning project
090|Azure Data Engineering|SQL|SQL quality and operations|Schema tests;Null tests;Uniqueness tests;Referential-integrity tests;Reconciliation;Freshness tests;Transaction control;Error recovery;SQL deployment;Data-quality capstone
091|Azure Data Engineering|Data Engineering Fundamentals|Modern data architecture|Data-platform components;Data warehouse;Data lake;Lakehouse;Data mesh;Lambda architecture;Kappa architecture;Medallion architecture;Technology selection;Architecture case study
092|Azure Data Engineering|Data Engineering Fundamentals|Batch data engineering|Batch-processing concepts;ETL versus ELT;Scheduling;Dependencies;Incremental processing;Backfills;Late data;Idempotency;Batch monitoring;Batch-platform project
093|Azure Data Engineering|Data Engineering Fundamentals|Streaming data engineering|Event-stream concepts;Producers and consumers;Partitions;Offsets;Delivery guarantees;Event time;Windows;Watermarks;Streaming reliability;Streaming architecture project
094|Azure Data Engineering|Data Engineering Fundamentals|Data modeling and governance|Conceptual models;Logical models;Physical models;Dimensional modeling;Data vault concepts;Metadata management;Data catalogues;Lineage;Data ownership;Governed-model project
095|Azure Data Engineering|Data Engineering Fundamentals|Reliable secure and economical platforms|Reliability objectives;Data observability;Security layers;Identity and access;Encryption;Privacy;Disaster recovery;Cost allocation;FinOps optimization;Platform-design capstone
096|Azure Data Engineering|Azure Data Factory|ADF foundations|ADF architecture;Factories and resources;Linked services;Datasets;Pipelines;Activities;Authoring interface;Publish model;First pipeline;ADF foundations project
097|Azure Data Engineering|Azure Data Factory|Copy Activity and Mapping Data Flows|Copy Activity;Source configuration;Sink configuration;Schema mapping;Fault tolerance;Data-flow foundations;Transformations;Debug sessions;Data-flow performance;Copy-and-transform project
098|Azure Data Engineering|Azure Data Factory|Parameters and metadata-driven pipelines|Pipeline parameters;Dataset parameters;Variables;Expressions;System variables;Lookup Activity;ForEach Activity;Metadata tables;Dynamic paths;Metadata-driven project
099|Azure Data Engineering|Azure Data Factory|Control flow and triggers|Dependency conditions;If Condition;Switch Activity;Until Activity;Execute Pipeline;Schedule triggers;Tumbling-window triggers;Event triggers;Trigger recovery;Orchestration project
100|Azure Data Engineering|Azure Data Factory|Integration Runtime and security|Azure Integration Runtime;Self-hosted Integration Runtime;Managed virtual networks;Private endpoints;Managed identity;Key Vault integration;RBAC;Network troubleshooting;Secure connectivity;Secure-ADF project
101|Azure Data Engineering|Azure Data Factory|ADF monitoring and CI/CD|Pipeline monitoring;Activity diagnostics;Alerts;Reruns and recovery;Git integration;Branching workflow;ARM deployment;Environment parameters;Release validation;Production-ADF capstone
102|Azure Data Engineering|ADLS Gen2|ADLS Gen2 foundations|Storage-account architecture;Hierarchical namespace;Containers and directories;Blob types;Naming standards;Storage tiers;Redundancy options;Azure CLI access;SDK access;Data-lake foundations project
103|Azure Data Engineering|ADLS Gen2|ADLS security|Entra ID authentication;Shared keys;SAS tokens;RBAC;POSIX ACLs;Default ACLs;Private endpoints;Firewalls;Encryption;Secure-lake project
104|Azure Data Engineering|ADLS Gen2|Lake organization and lifecycle|Raw-zone design;Curated-zone design;Serving-zone design;Partitioning;File sizing;Naming conventions;Lifecycle policies;Versioning;Soft delete;Lake-organization project
105|Azure Data Engineering|ADLS Gen2|ADLS integrations and operations|ADF integration;Databricks integration;Synapse integration;Fabric integration;Event Grid;Monitoring metrics;Diagnostic logs;Performance tuning;Disaster recovery;ADLS capstone
106|Azure Data Engineering|Azure Databricks|Databricks workspace foundations|Workspace architecture;Notebooks;Compute types;Cluster configuration;Libraries;Repos and Git;Widgets;Secrets;Workspace organization;Databricks foundations project
107|Azure Data Engineering|Azure Databricks|Spark data engineering in Databricks|SparkSession;DataFrame ingestion;Transformations;Aggregations;Joins;Window functions;Spark SQL;User-defined functions;Data writing;Spark pipeline project
108|Azure Data Engineering|Azure Databricks|Delta Lake and lakehouse architecture|Delta tables;ACID transactions;Schema enforcement;Schema evolution;MERGE;Time travel;Change Data Feed;Optimization;Medallion architecture;Lakehouse project
109|Azure Data Engineering|Azure Databricks|Databricks workflows and managed pipelines|Jobs;Tasks;Dependencies;Parameters;Scheduling;Retries;Managed pipeline concepts;Data-quality expectations;Workflow monitoring;Production workflow project
110|Azure Data Engineering|Azure Databricks|Unity Catalog and security|Unity Catalog architecture;Metastores;Catalogues and schemas;Managed and external tables;Storage credentials;External locations;Privileges;Row and column controls;Lineage;Governed-lakehouse project
111|Azure Data Engineering|Azure Databricks|Databricks performance and deployment|Query plans;Adaptive execution;Partition tuning;File compaction;Data skipping;Photon concepts;Cost controls;Testing;CI/CD;Databricks capstone
112|Azure Data Engineering|PySpark|Spark and PySpark architecture|Distributed-computing concepts;Driver and executors;SparkSession;Jobs stages and tasks;Lazy evaluation;Transformations and actions;Narrow and wide operations;DAG inspection;Local setup;Architecture lab
113|Azure Data Engineering|PySpark|DataFrame transformations|Creating DataFrames;Selecting columns;Filtering;Adding columns;Renaming and dropping;Conditional expressions;Sorting;Deduplication;Sampling;Transformation project
114|Azure Data Engineering|PySpark|PySpark functions and data types|Spark SQL types;Schema definitions;Null handling;String functions;Date functions;Array functions;Map functions;Struct functions;Type conversion;Complex-data project
115|Azure Data Engineering|PySpark|Joins aggregations and windows|GroupBy;Aggregate functions;Inner joins;Outer joins;Semi and anti joins;Join strategies;Window specifications;Ranking;Running calculations;Analytical pipeline project
116|Azure Data Engineering|PySpark|PySpark input output and partitioning|CSV;JSON;Parquet;Delta;JDBC;Read options;Write modes;Partitioned writes;Small-file control;Multi-source project
117|Azure Data Engineering|PySpark|PySpark performance and testing|Explain plans;Shuffle reduction;Repartition and coalesce;Broadcast joins;Caching;UDF alternatives;Memory tuning;Unit testing;DataFrame assertions;Performance project
118|Azure Data Engineering|PySpark|Structured Streaming|Streaming DataFrames;Sources and sinks;Output modes;Checkpoints;Event time;Watermarks;Window aggregations;Streaming joins;Recovery;PySpark streaming capstone
119|Azure Data Engineering|Azure Synapse Analytics|Synapse architecture|Synapse workspace;Synapse Studio;SQL pools;Spark pools;Pipelines;Storage integration;Linked services;Security model;Monitoring;Synapse architecture project
120|Azure Data Engineering|Azure Synapse Analytics|Synapse SQL|Serverless SQL;External tables;OPENROWSET;Dedicated SQL pools;Distribution strategies;Columnstore indexes;Partitioning;Workload management;Query tuning;Synapse SQL project
121|Azure Data Engineering|Azure Synapse Analytics|Synapse Spark and pipelines|Spark notebooks;DataFrame processing;Delta integration;Lake databases;Pipeline activities;Parameters;Triggers;Notebook orchestration;Integrated monitoring;End-to-end Synapse project
122|Azure Data Engineering|Azure Synapse Analytics|Synapse production engineering|Managed identity;Private networking;Access controls;Data protection;Source control;CI/CD;Performance baselines;Cost management;Disaster recovery;Synapse capstone
123|Azure Data Engineering|Microsoft Fabric|Microsoft Fabric and OneLake|Fabric architecture;Capacities;Workspaces;OneLake;Lakehouses;Shortcuts;Domains;Item permissions;Monitoring Hub;Fabric foundations project
124|Azure Data Engineering|Microsoft Fabric|Fabric Data Factory and Data Engineering|Fabric pipelines;Copy Activity;Dataflows Gen2;Connections;Parameters;Fabric notebooks;Spark jobs;Delta tables;Scheduling;Fabric engineering project
125|Azure Data Engineering|Microsoft Fabric|Warehousing real-time intelligence and BI|Fabric Warehouse;SQL endpoint;Semantic models;Direct Lake;Real-Time Intelligence;Eventstreams;KQL databases;Power BI integration;End-to-end analytics;Analytics project
126|Azure Data Engineering|Microsoft Fabric|Fabric governance and deployment|Purview integration;Lineage;Sensitivity labels;Access control;Deployment pipelines;Git integration;Monitoring;Capacity optimization;Disaster recovery;Fabric capstone
127|Azure Data Engineering|Delta Lake|Delta-table foundations|Delta architecture;Transaction log;Creating tables;Reading and writing;ACID properties;Table history;Time travel;Constraints;Table inspection;Delta foundations project
128|Azure Data Engineering|Delta Lake|Schema and change processing|Schema enforcement;Schema evolution;MERGE;Upserts;Deletes;Change Data Feed;Slowly changing dimensions;Deduplication;Incremental processing;Change-processing project
129|Azure Data Engineering|Delta Lake|Delta performance and reliability|Partitioning;Compaction;Optimize operations;Data skipping;Clustering concepts;Vacuum;Retention;Concurrent writes;Recovery;Performance project
130|Azure Data Engineering|Delta Lake|Streaming and governed Delta Lake|Streaming reads;Streaming writes;Checkpoints;Exactly-once concepts;Medallion pipelines;Table permissions;Lineage;Quality expectations;Operational monitoring;Delta Lake capstone
"""


AZURE_DEVOPS = """
131|Azure DevOps|Linux & Shell Scripting|Linux command-line foundations|Linux filesystem;Navigation commands;File inspection;File creation and removal;Copy and move operations;Finding files;Text filters;Pipes and redirection;Help and documentation;Command-line practice lab
132|Azure DevOps|Linux & Shell Scripting|Shell scripting foundations|Script structure;Variables;Quoting;Command substitution;Conditionals;Loops;Functions;Exit codes;Input arguments;Automation-script project
133|Azure DevOps|Linux & Shell Scripting|Linux systems administration|Users and groups;File permissions;Processes;Signals;Services with systemd;Package management;Environment configuration;Storage inspection;Network diagnostics;Administration lab
134|Azure DevOps|Linux & Shell Scripting|Production shell automation|Strict mode;Error handling;Logging;Temporary files;Idempotent scripts;Configuration files;Secrets handling;Scheduled jobs;Shell testing;Operations capstone
135|Azure DevOps|Git & Version Control|Git foundations|Version-control concepts;Repository initialization;Working tree and index;Commits;Status and diffs;File history;Ignoring files;Tags;Remote repositories;Git foundations project
136|Azure DevOps|Git & Version Control|Branching and integration|Branch concepts;Creating branches;Merging;Merge conflicts;Rebasing;Interactive rebase;Cherry-picking;Release branches;Trunk-based development;Branching lab
137|Azure DevOps|Git & Version Control|Collaborative Git workflows|Clone and fetch;Pull and push;Tracking branches;Pull requests;Code review;Commit conventions;Fork workflows;Protected branches;Team policies;Collaboration project
138|Azure DevOps|Git & Version Control|Advanced Git and recovery|Reflog;Reset modes;Revert;Restore;Bisect;Stashing;Hooks;Submodules;Repository maintenance;Git recovery capstone
139|Azure DevOps|Azure Repos|Azure Repos foundations|Azure DevOps organizations;Projects and repositories;Repository creation;Clone authentication;Branch management;Pull requests;Reviewer workflows;Repository permissions;Search and history;Azure Repos project
140|Azure DevOps|Azure Repos|Policies security and integrations|Branch policies;Build validation;Required reviewers;Status checks;Path filters;Service connections;SSH and tokens;Audit logs;GitHub interoperability;Governed-repository capstone
141|Azure DevOps|Azure Pipelines|Continuous integration foundations|CI principles;Agents and pools;Pipeline anatomy;Triggers;Checkout;Build stages;Test stages;Artifacts;Pipeline variables;First CI pipeline
142|Azure DevOps|Azure Pipelines|Build and test automation|Dependency caching;Matrix builds;Unit tests;Integration tests;Code coverage;Static analysis;Package creation;Artifact publishing;Quality gates;Build-pipeline project
143|Azure DevOps|Azure Pipelines|Continuous delivery and release|CD principles;Environments;Deployment jobs;Service connections;Secrets;Approvals and checks;Release artifacts;Database delivery;Rollback design;Delivery-pipeline project
144|Azure DevOps|Azure Pipelines|Deployment strategies and environments|Rolling deployments;Blue-green deployments;Canary releases;Feature flags;Ring deployments;Environment promotion;Health checks;Automated rollback;Release evidence;Strategy lab
145|Azure DevOps|Azure Pipelines|Pipeline operations and governance|Pipeline permissions;Variable groups;Secure files;Retention;Concurrency;Failure diagnosis;Reruns;Cost optimization;Pipeline analytics;Azure Pipelines capstone
146|Azure DevOps|YAML Pipeline Development|YAML pipeline foundations|YAML syntax;Pipeline schema;Stages jobs and steps;Tasks and scripts;Variables;Parameters;Triggers;Agent selection;Expressions;Foundations pipeline
147|Azure DevOps|YAML Pipeline Development|Templates and reusable pipelines|Step templates;Job templates;Stage templates;Variable templates;Template parameters;Object parameters;Extends templates;Template repositories;Versioning templates;Reusable-pipeline project
148|Azure DevOps|YAML Pipeline Development|Conditions dependencies and artifacts|Runtime expressions;Compile-time expressions;Conditions;Output variables;Job dependencies;Stage dependencies;Artifact download;Pipeline resources;Multi-repository checkout;Orchestration lab
149|Azure DevOps|YAML Pipeline Development|Secure production YAML|Secret variables;Key Vault integration;Service connections;Least privilege;Approval checks;Policy templates;Validation;Testing pipeline changes;Documentation;YAML capstone
150|Azure DevOps|Docker & Containerization|Container foundations|Containers versus virtual machines;Docker architecture;Installing Docker;Images and containers;Container lifecycle;Port publishing;Environment variables;Logs;Resource limits;First container project
151|Azure DevOps|Docker & Containerization|Building Docker images|Dockerfile syntax;Base-image selection;Build context;Layer caching;Multi-stage builds;Build arguments;Image metadata;Non-root users;Image testing;Optimized-image project
152|Azure DevOps|Docker & Containerization|Docker networking and storage|Network drivers;Bridge networks;DNS and service discovery;Port mapping;Volumes;Bind mounts;Storage permissions;Backup and restore;Network troubleshooting;Stateful-container lab
153|Azure DevOps|Docker & Containerization|Compose and container registries|Compose files;Multi-service applications;Dependencies;Profiles;Configuration;Health checks;Registry concepts;Azure Container Registry;Image tagging;Compose project
154|Azure DevOps|Docker & Containerization|Container security and production practices|Image scanning;Supply-chain metadata;Secrets;Capabilities;Read-only filesystems;Runtime security;Image signing;Patch strategy;Observability;Docker capstone
155|Azure DevOps|Kubernetes & AKS|Kubernetes architecture|Cluster components;Control plane;Worker nodes;API objects;Namespaces;Labels and selectors;kubectl;Declarative management;Resource specifications;Architecture lab
156|Azure DevOps|Kubernetes & AKS|Kubernetes workload objects|Pods;ReplicaSets;Deployments;StatefulSets;DaemonSets;Jobs;CronJobs;Probes;Resource requests and limits;Workload project
157|Azure DevOps|Kubernetes & AKS|Configuration and storage|ConfigMaps;Secrets;Environment injection;Volumes;PersistentVolumes;PersistentVolumeClaims;StorageClasses;Azure Disk;Azure Files;Stateful-workload project
158|Azure DevOps|Kubernetes & AKS|Kubernetes networking and ingress|Cluster networking;Services;ClusterIP;NodePort;LoadBalancer;Ingress;Ingress controllers;Network policies;DNS troubleshooting;Networking lab
159|Azure DevOps|Kubernetes & AKS|Scaling upgrades and operations|Horizontal Pod Autoscaler;Vertical scaling;Cluster autoscaler;Pod disruption budgets;Rolling updates;Rollbacks;Helm;Logging;Metrics;Operations project
160|Azure DevOps|Kubernetes & AKS|Production Azure Kubernetes Service|AKS architecture;Cluster creation;Entra integration;Managed identities;ACR integration;Node pools;Private clusters;Azure Policy;Upgrade planning;AKS capstone
161|Azure DevOps|Terraform Infrastructure as Code|Terraform foundations|Infrastructure as Code;Terraform workflow;HCL syntax;Providers;Resources;Data sources;Variables;Outputs;Plan and apply;Foundations project
162|Azure DevOps|Terraform Infrastructure as Code|Provisioning Azure with Terraform|Azure provider;Authentication;Resource groups;Virtual networks;Storage accounts;Compute resources;Dependencies;Tags;Naming standards;Azure provisioning project
163|Azure DevOps|Terraform Infrastructure as Code|Terraform state and lifecycle|State purpose;Remote backends;State locking;State commands;Import;Moved blocks;Lifecycle meta-arguments;Drift detection;State recovery;State-management lab
164|Azure DevOps|Terraform Infrastructure as Code|Modules testing and automation|Module design;Inputs and outputs;Module composition;Version constraints;Validation rules;Formatting and validation;Plan testing;Policy checks;CI integration;Reusable-module project
165|Azure DevOps|Terraform Infrastructure as Code|Production Terraform platforms|Environment strategy;Workspace tradeoffs;Repository layout;Identity and secrets;Pipeline approvals;Safe apply;Observability;Cost estimation;Disaster recovery;Terraform capstone
166|Azure DevOps|Azure Cloud Services|Azure solution architecture|Subscriptions and management groups;Resource groups;Regions and availability zones;Compute choices;Storage choices;Database choices;Integration services;Architecture framework;Cost estimation;Architecture case study
167|Azure DevOps|Azure Cloud Services|Azure identity networking and operations|Microsoft Entra ID;Managed identities;RBAC;Virtual networks;Private endpoints;DNS;Azure Monitor;Log Analytics;Backup and recovery;Cloud-operations capstone
168|Azure DevOps|DevSecOps & Monitoring|DevSecOps foundations and supply-chain security|Shift-left security;Threat modeling;Secure coding;Dependency scanning;Secret scanning;SAST;DAST;Container scanning;Software bills of materials;Security-pipeline project
169|Azure DevOps|DevSecOps & Monitoring|Observability and incident response|Logs metrics and traces;Telemetry design;Service-level indicators;Service-level objectives;Dashboards;Alert design;Distributed tracing;Incident response;Post-incident reviews;Observability project
170|Azure DevOps|DevSecOps & Monitoring|Secure delivery and monitoring capstone|Security architecture;Policy as code;Identity controls;Release controls;Runtime protection;Vulnerability management;Compliance evidence;Resilience testing;Operational readiness;DevSecOps capstone
"""

INTERVIEW_QUESTIONS = """
171|Interview Questions|Full Stack AI|Python and SQL interview preparation|Python language questions;Collections and complexity;Functions and object design;Testing and debugging;Python coding patterns;SQL query fundamentals;Joins and subqueries;Window functions;SQL optimization;Mock Python-and-SQL interview
172|Interview Questions|Full Stack AI|Data science and statistics interviews|Descriptive statistics;Probability questions;Sampling;Hypothesis testing;Confidence intervals;Experiment design;Data cleaning scenarios;Exploratory analysis;Visualization communication;Mock analytics interview
173|Interview Questions|Full Stack AI|Machine-learning interviews|ML foundations;Feature engineering;Model selection;Regression questions;Classification questions;Tree-model questions;Evaluation metrics;Overfitting and regularization;Deployment scenarios;Mock ML interview
174|Interview Questions|Full Stack AI|Deep learning and generative-AI interviews|Neural-network foundations;Backpropagation;Optimization;CNN questions;Sequence-model questions;Transformer architecture;Generative-model concepts;Prompt engineering;Safety and evaluation;Mock deep-learning interview
175|Interview Questions|Full Stack AI|LLM RAG and agent interviews|Tokenization and embeddings;LLM inference;Fine-tuning tradeoffs;RAG architecture;Retrieval evaluation;Grounded generation;Tool calling;Agent planning;Agent safety;Mock LLM-systems interview
176|Interview Questions|Full Stack AI|AI system design and behavioral interviews|Requirements clarification;Architecture decomposition;Data and model choices;Scale and latency;Reliability;Security and governance;Cost tradeoffs;Project storytelling;Behavioral frameworks;Full Stack AI interview capstone
177|Interview Questions|Azure Data Engineering|Data engineering and SQL interviews|Data architecture;ETL versus ELT;Batch and streaming;Dimensional modeling;SQL transformations;Data quality;Incremental loading;Reliability scenarios;Performance tuning;Mock data-engineering interview
178|Interview Questions|Azure Data Engineering|Azure storage and orchestration interviews|ADLS architecture;Storage security;ADF components;Copy Activity;Metadata-driven pipelines;Triggers;Integration Runtime;Managed identity;Monitoring scenarios;Mock ADF-and-ADLS interview
179|Interview Questions|Azure Data Engineering|Spark Databricks and Delta interviews|Spark architecture;DataFrame operations;Joins and shuffles;Partition tuning;Structured Streaming;Databricks workflows;Delta transactions;Unity Catalog;Performance scenarios;Mock lakehouse interview
180|Interview Questions|Azure Data Engineering|Synapse and Fabric interviews|Synapse architecture;Serverless SQL;Dedicated pools;Synapse Spark;Fabric architecture;OneLake;Fabric pipelines;Direct Lake;Governance scenarios;Mock analytics-platform interview
181|Interview Questions|Azure Data Engineering|Azure data-platform system design|Requirement discovery;Source assessment;Ingestion design;Storage zones;Transformation design;Serving patterns;Governance;Observability;Cost and resilience;Azure data interview capstone
182|Interview Questions|Azure DevOps|Linux Git and repository interviews|Linux command line;Shell scripting;Process troubleshooting;Git internals;Branching strategies;Conflict resolution;Pull-request practices;Azure Repos policies;Scenario questions;Mock foundations interview
183|Interview Questions|Azure DevOps|CI/CD and YAML interviews|CI principles;CD principles;Pipeline architecture;YAML expressions;Templates;Artifacts;Deployment strategies;Secrets;Failure diagnosis;Mock pipeline interview
184|Interview Questions|Azure DevOps|Docker Kubernetes and AKS interviews|Container concepts;Dockerfiles;Container networking;Kubernetes architecture;Workload objects;Kubernetes networking;Storage;Scaling;AKS security;Mock platform interview
185|Interview Questions|Azure DevOps|Terraform security and operations interviews|Terraform workflow;State management;Modules;Azure architecture;Identity and RBAC;DevSecOps controls;Observability;Incident response;System design;Azure DevOps interview capstone
"""

PROJECT_FLOWS = """
186|Project Flows|Full Stack AI|AI product discovery and architecture flow|Business problem;User journeys;Success metrics;Data feasibility;Model feasibility;Risk assessment;Architecture options;Delivery roadmap;Experiment plan;Discovery deliverable
187|Project Flows|Full Stack AI|Data and feature delivery flow|Source contracts;Ingestion;Validation;Cleaning;Exploration;Feature design;Feature pipelines;Versioning;Quality monitoring;Reusable data product
188|Project Flows|Full Stack AI|Machine-learning product flow|Baseline model;Training pipeline;Experiment tracking;Evaluation;Error analysis;Model packaging;Serving API;Deployment;Monitoring;ML product release
189|Project Flows|Full Stack AI|Generative-AI application flow|Use-case boundaries;Model selection;Prompt design;Structured outputs;Tool integration;Guardrails;Evaluation suite;Application deployment;Observability;GenAI product release
190|Project Flows|Full Stack AI|Production RAG flow|Knowledge-source inventory;Document ingestion;Chunking;Embedding selection;Index construction;Retrieval design;Grounded generation;RAG evaluation;Access control;Production RAG release
191|Project Flows|Full Stack AI|Agentic-AI delivery flow|Workflow selection;Tool contracts;Planning design;Memory design;Permission model;Agent evaluation;Human oversight;Durable execution;Monitoring;Agentic-AI capstone
192|Project Flows|Azure Data Engineering|Azure data-platform discovery flow|Business outcomes;Source inventory;Volume and velocity;Data classification;Consumer needs;Service selection;Security baseline;Cost model;Delivery roadmap;Architecture decision record
193|Project Flows|Azure Data Engineering|Ingestion and lake foundation flow|Landing-zone setup;ADLS zones;Identity and networking;ADF connections;Batch ingestion;Streaming ingestion;Metadata framework;Data validation;Operational logging;Ingestion release
194|Project Flows|Azure Data Engineering|Lakehouse transformation flow|Bronze design;Silver transformations;Gold models;Spark engineering;Delta tables;Incremental processing;Workflow orchestration;Data-quality expectations;Performance optimization;Lakehouse release
195|Project Flows|Azure Data Engineering|Analytics serving and governance flow|Warehouse design;Synapse serving;Fabric serving;Semantic models;Access controls;Catalogue and lineage;Privacy controls;Consumer testing;Service objectives;Governed analytics release
196|Project Flows|Azure Data Engineering|Data-platform deployment and operations flow|Source control;Environment strategy;Infrastructure automation;Pipeline CI/CD;Testing gates;Monitoring;Incident response;Disaster recovery;Cost optimization;Azure data-platform capstone
197|Project Flows|Azure DevOps|DevOps platform discovery flow|Application assessment;Team topology;Repository strategy;Environment model;Security requirements;Toolchain selection;Delivery metrics;Governance;Adoption roadmap;Platform blueprint
198|Project Flows|Azure DevOps|CI/CD implementation flow|Repository policies;Build pipeline;Automated tests;Artifact strategy;Environment promotion;Deployment strategy;Approvals;Rollback;Pipeline observability;CI/CD release
199|Project Flows|Azure DevOps|Container and AKS delivery flow|Application containerization;Image optimization;Registry setup;AKS foundation;Workload manifests;Networking and ingress;Secrets and identity;Scaling;Monitoring;AKS release
200|Project Flows|Azure DevOps|Infrastructure DevSecOps and operations flow|Terraform modules;Remote state;Infrastructure pipelines;Policy as code;Security scanning;Azure monitoring;Incident runbooks;Resilience tests;Compliance evidence;Azure DevOps capstone
"""


def _parse(text: str) -> list[Topic]:
    topics: list[Topic] = []
    for line in text.strip().splitlines():
        raw_number, section, course, title, raw_lessons = line.split("|", maxsplit=4)
        lessons = tuple(item.strip() for item in raw_lessons.split(";"))
        topics.append(Topic(int(raw_number), section, course, title, lessons))
    return topics


def load_catalog() -> list[Topic]:
    topics = _parse(FULL_STACK_AI)
    topics += _parse(AZURE_DATA_ENGINEERING)
    topics += _parse(AZURE_DEVOPS)
    topics += _parse(INTERVIEW_QUESTIONS)
    topics += _parse(PROJECT_FLOWS)
    return topics
